// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package ffi_rpc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type FfiRpcFrame struct {
	_tab flatbuffers.Table
}

func GetRootAsFfiRpcFrame(buf []byte, offset flatbuffers.UOffsetT) *FfiRpcFrame {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &FfiRpcFrame{}
	x.Init(buf, n+offset)
	return x
}

func FinishFfiRpcFrameBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsFfiRpcFrame(buf []byte, offset flatbuffers.UOffsetT) *FfiRpcFrame {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &FfiRpcFrame{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedFfiRpcFrameBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *FfiRpcFrame) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *FfiRpcFrame) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *FfiRpcFrame) Header(obj *FfiRpcHeader) *FfiRpcHeader {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := o + rcv._tab.Pos
		if obj == nil {
			obj = new(FfiRpcHeader)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *FfiRpcFrame) Bytes(j int) int8 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetInt8(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *FfiRpcFrame) BytesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *FfiRpcFrame) MutateBytes(j int, n int8) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateInt8(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func FfiRpcFrameStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func FfiRpcFrameAddHeader(builder *flatbuffers.Builder, header flatbuffers.UOffsetT) {
	builder.PrependStructSlot(0, flatbuffers.UOffsetT(header), 0)
}
func FfiRpcFrameAddBytes(builder *flatbuffers.Builder, bytes flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(bytes), 0)
}
func FfiRpcFrameStartBytesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func FfiRpcFrameEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
