// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package ffi_rpc

import "strconv"

type FfiRpcDiscoveryType uint32

const (
	FfiRpcDiscoveryTypenone             FfiRpcDiscoveryType = 0
	FfiRpcDiscoveryTypepartner_self_in  FfiRpcDiscoveryType = 1
	FfiRpcDiscoveryTypepartner_self_out FfiRpcDiscoveryType = 2
)

var EnumNamesFfiRpcDiscoveryType = map[FfiRpcDiscoveryType]string{
	FfiRpcDiscoveryTypenone:             "none",
	FfiRpcDiscoveryTypepartner_self_in:  "partner_self_in",
	FfiRpcDiscoveryTypepartner_self_out: "partner_self_out",
}

var EnumValuesFfiRpcDiscoveryType = map[string]FfiRpcDiscoveryType{
	"none":             FfiRpcDiscoveryTypenone,
	"partner_self_in":  FfiRpcDiscoveryTypepartner_self_in,
	"partner_self_out": FfiRpcDiscoveryTypepartner_self_out,
}

func (v FfiRpcDiscoveryType) String() string {
	if s, ok := EnumNamesFfiRpcDiscoveryType[v]; ok {
		return s
	}
	return "FfiRpcDiscoveryType(" + strconv.FormatInt(int64(v), 10) + ")"
}
