// automatically generated by the FlatBuffers compiler, do not modify

package net_data_type

@Suppress("unused")
class NetDataType private constructor() {
    companion object {
        const val none: UInt = 0u
        const val net_discovery: UInt = 1u
        const val chat: UInt = 2u
    }
}
