[package]
name = "idl"
version.workspace = true
edition.workspace = true

[dependencies]

log.workspace = true
uuid.workspace = true
ulid.workspace = true

flatbuffers.workspace = true

x25519-dalek.workspace = true