// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package net_data_type

import "strconv"

type NetDataType uint32

const (
	NetDataTypenone          NetDataType = 0
	NetDataTypenet_discovery NetDataType = 1
	NetDataTypechat          NetDataType = 2
)

var EnumNamesNetDataType = map[NetDataType]string{
	NetDataTypenone:          "none",
	NetDataTypenet_discovery: "net_discovery",
	NetDataTypechat:          "chat",
}

var EnumValuesNetDataType = map[string]NetDataType{
	"none":          NetDataTypenone,
	"net_discovery": NetDataTypenet_discovery,
	"chat":          NetDataTypechat,
}

func (v NetDataType) String() string {
	if s, ok := EnumNamesNetDataType[v]; ok {
		return s
	}
	return "NetDataType(" + strconv.FormatInt(int64(v), 10) + ")"
}
