// automatically generated by the FlatBuffers compiler, do not modify
// ignore_for_file: unused_import, unused_field, unused_element, unused_local_variable, constant_identifier_names

library base;

import 'dart:typed_data' show Uint8List;
import 'package:flat_buffers/flat_buffers.dart' as fb;

enum HeaderType {
  none(0),
  net_discovery(1),
  chat(2),
  ffi_rpc(3),
  error_info(2147483647);

  final int value;
  const HeaderType(this.value);

  factory HeaderType.fromValue(int value) {
    switch (value) {
      case 0:
        return HeaderType.none;
      case 1:
        return HeaderType.net_discovery;
      case 2:
        return HeaderType.chat;
      case 3:
        return HeaderType.ffi_rpc;
      case 2147483647:
        return HeaderType.error_info;
      default:
        throw StateError('Invalid value $value for bit flag enum');
    }
  }

  static HeaderType? _createOrNull(int? value) => value == null ? null : HeaderType.fromValue(value);

  static const int minValue = 0;
  static const int maxValue = 2147483647;
  static const fb.Reader<HeaderType> reader = _HeaderTypeReader();
}

class _HeaderTypeReader extends fb.Reader<HeaderType> {
  const _HeaderTypeReader();

  @override
  int get size => 4;

  @override
  HeaderType read(fb.BufferContext bc, int offset) => HeaderType.fromValue(const fb.Uint32Reader().read(bc, offset));
}

class UlidBytes {
  UlidBytes._(this._bc, this._bcOffset);

  static const fb.Reader<UlidBytes> reader = _UlidBytesReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  int get low => const fb.Uint64Reader().read(_bc, _bcOffset + 0);
  int get high => const fb.Uint64Reader().read(_bc, _bcOffset + 8);

  @override
  String toString() {
    return 'UlidBytes{low: ${low}, high: ${high}}';
  }

  UlidBytesT unpack() => UlidBytesT(low: low, high: high);

  static int pack(fb.Builder fbBuilder, UlidBytesT? object) {
    if (object == null) return 0;
    return object.pack(fbBuilder);
  }
}

class UlidBytesT implements fb.Packable {
  int low;
  int high;

  UlidBytesT({required this.low, required this.high});

  @override
  int pack(fb.Builder fbBuilder) {
    fbBuilder.putUint64(high);
    fbBuilder.putUint64(low);
    return fbBuilder.offset;
  }

  @override
  String toString() {
    return 'UlidBytesT{low: ${low}, high: ${high}}';
  }
}

class _UlidBytesReader extends fb.StructReader<UlidBytes> {
  const _UlidBytesReader();

  @override
  int get size => 16;

  @override
  UlidBytes createObject(fb.BufferContext bc, int offset) => UlidBytes._(bc, offset);
}

class UlidBytesBuilder {
  UlidBytesBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  int finish(int low, int high) {
    fbBuilder.putUint64(high);
    fbBuilder.putUint64(low);
    return fbBuilder.offset;
  }
}

class UlidBytesObjectBuilder extends fb.ObjectBuilder {
  final int _low;
  final int _high;

  UlidBytesObjectBuilder({required int low, required int high}) : _low = low, _high = high;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    fbBuilder.putUint64(_high);
    fbBuilder.putUint64(_low);
    return fbBuilder.offset;
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}

class UuidV7Bytes {
  UuidV7Bytes._(this._bc, this._bcOffset);

  static const fb.Reader<UuidV7Bytes> reader = _UuidV7BytesReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  int get low => const fb.Uint64Reader().read(_bc, _bcOffset + 0);
  int get high => const fb.Uint64Reader().read(_bc, _bcOffset + 8);

  @override
  String toString() {
    return 'UuidV7Bytes{low: ${low}, high: ${high}}';
  }

  UuidV7BytesT unpack() => UuidV7BytesT(low: low, high: high);

  static int pack(fb.Builder fbBuilder, UuidV7BytesT? object) {
    if (object == null) return 0;
    return object.pack(fbBuilder);
  }
}

class UuidV7BytesT implements fb.Packable {
  int low;
  int high;

  UuidV7BytesT({required this.low, required this.high});

  @override
  int pack(fb.Builder fbBuilder) {
    fbBuilder.putUint64(high);
    fbBuilder.putUint64(low);
    return fbBuilder.offset;
  }

  @override
  String toString() {
    return 'UuidV7BytesT{low: ${low}, high: ${high}}';
  }
}

class _UuidV7BytesReader extends fb.StructReader<UuidV7Bytes> {
  const _UuidV7BytesReader();

  @override
  int get size => 16;

  @override
  UuidV7Bytes createObject(fb.BufferContext bc, int offset) => UuidV7Bytes._(bc, offset);
}

class UuidV7BytesBuilder {
  UuidV7BytesBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  int finish(int low, int high) {
    fbBuilder.putUint64(high);
    fbBuilder.putUint64(low);
    return fbBuilder.offset;
  }
}

class UuidV7BytesObjectBuilder extends fb.ObjectBuilder {
  final int _low;
  final int _high;

  UuidV7BytesObjectBuilder({required int low, required int high}) : _low = low, _high = high;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    fbBuilder.putUint64(_high);
    fbBuilder.putUint64(_low);
    return fbBuilder.offset;
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}

class Ipv6 {
  Ipv6._(this._bc, this._bcOffset);

  static const fb.Reader<Ipv6> reader = _Ipv6Reader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  int get ub1 => const fb.Uint8Reader().read(_bc, _bcOffset + 0);
  int get ub2 => const fb.Uint8Reader().read(_bc, _bcOffset + 1);
  int get ub3 => const fb.Uint8Reader().read(_bc, _bcOffset + 2);
  int get ub4 => const fb.Uint8Reader().read(_bc, _bcOffset + 3);
  int get ub5 => const fb.Uint8Reader().read(_bc, _bcOffset + 4);
  int get ub6 => const fb.Uint8Reader().read(_bc, _bcOffset + 5);
  int get ub7 => const fb.Uint8Reader().read(_bc, _bcOffset + 6);
  int get ub8 => const fb.Uint8Reader().read(_bc, _bcOffset + 7);
  int get ub9 => const fb.Uint8Reader().read(_bc, _bcOffset + 8);
  int get ub10 => const fb.Uint8Reader().read(_bc, _bcOffset + 9);
  int get ub11 => const fb.Uint8Reader().read(_bc, _bcOffset + 10);
  int get ub12 => const fb.Uint8Reader().read(_bc, _bcOffset + 11);
  int get ub13 => const fb.Uint8Reader().read(_bc, _bcOffset + 12);
  int get ub14 => const fb.Uint8Reader().read(_bc, _bcOffset + 13);
  int get ub15 => const fb.Uint8Reader().read(_bc, _bcOffset + 14);
  int get ub16 => const fb.Uint8Reader().read(_bc, _bcOffset + 15);

  @override
  String toString() {
    return 'Ipv6{ub1: ${ub1}, ub2: ${ub2}, ub3: ${ub3}, ub4: ${ub4}, ub5: ${ub5}, ub6: ${ub6}, ub7: ${ub7}, ub8: ${ub8}, ub9: ${ub9}, ub10: ${ub10}, ub11: ${ub11}, ub12: ${ub12}, ub13: ${ub13}, ub14: ${ub14}, ub15: ${ub15}, ub16: ${ub16}}';
  }

  Ipv6T unpack() => Ipv6T(
    ub1: ub1,
    ub2: ub2,
    ub3: ub3,
    ub4: ub4,
    ub5: ub5,
    ub6: ub6,
    ub7: ub7,
    ub8: ub8,
    ub9: ub9,
    ub10: ub10,
    ub11: ub11,
    ub12: ub12,
    ub13: ub13,
    ub14: ub14,
    ub15: ub15,
    ub16: ub16,
  );

  static int pack(fb.Builder fbBuilder, Ipv6T? object) {
    if (object == null) return 0;
    return object.pack(fbBuilder);
  }
}

class Ipv6T implements fb.Packable {
  int ub1;
  int ub2;
  int ub3;
  int ub4;
  int ub5;
  int ub6;
  int ub7;
  int ub8;
  int ub9;
  int ub10;
  int ub11;
  int ub12;
  int ub13;
  int ub14;
  int ub15;
  int ub16;

  Ipv6T({
    required this.ub1,
    required this.ub2,
    required this.ub3,
    required this.ub4,
    required this.ub5,
    required this.ub6,
    required this.ub7,
    required this.ub8,
    required this.ub9,
    required this.ub10,
    required this.ub11,
    required this.ub12,
    required this.ub13,
    required this.ub14,
    required this.ub15,
    required this.ub16,
  });

  @override
  int pack(fb.Builder fbBuilder) {
    fbBuilder.putUint8(ub16);
    fbBuilder.putUint8(ub15);
    fbBuilder.putUint8(ub14);
    fbBuilder.putUint8(ub13);
    fbBuilder.putUint8(ub12);
    fbBuilder.putUint8(ub11);
    fbBuilder.putUint8(ub10);
    fbBuilder.putUint8(ub9);
    fbBuilder.putUint8(ub8);
    fbBuilder.putUint8(ub7);
    fbBuilder.putUint8(ub6);
    fbBuilder.putUint8(ub5);
    fbBuilder.putUint8(ub4);
    fbBuilder.putUint8(ub3);
    fbBuilder.putUint8(ub2);
    fbBuilder.putUint8(ub1);
    return fbBuilder.offset;
  }

  @override
  String toString() {
    return 'Ipv6T{ub1: ${ub1}, ub2: ${ub2}, ub3: ${ub3}, ub4: ${ub4}, ub5: ${ub5}, ub6: ${ub6}, ub7: ${ub7}, ub8: ${ub8}, ub9: ${ub9}, ub10: ${ub10}, ub11: ${ub11}, ub12: ${ub12}, ub13: ${ub13}, ub14: ${ub14}, ub15: ${ub15}, ub16: ${ub16}}';
  }
}

class _Ipv6Reader extends fb.StructReader<Ipv6> {
  const _Ipv6Reader();

  @override
  int get size => 16;

  @override
  Ipv6 createObject(fb.BufferContext bc, int offset) => Ipv6._(bc, offset);
}

class Ipv6Builder {
  Ipv6Builder(this.fbBuilder);

  final fb.Builder fbBuilder;

  int finish(
    int ub1,
    int ub2,
    int ub3,
    int ub4,
    int ub5,
    int ub6,
    int ub7,
    int ub8,
    int ub9,
    int ub10,
    int ub11,
    int ub12,
    int ub13,
    int ub14,
    int ub15,
    int ub16,
  ) {
    fbBuilder.putUint8(ub16);
    fbBuilder.putUint8(ub15);
    fbBuilder.putUint8(ub14);
    fbBuilder.putUint8(ub13);
    fbBuilder.putUint8(ub12);
    fbBuilder.putUint8(ub11);
    fbBuilder.putUint8(ub10);
    fbBuilder.putUint8(ub9);
    fbBuilder.putUint8(ub8);
    fbBuilder.putUint8(ub7);
    fbBuilder.putUint8(ub6);
    fbBuilder.putUint8(ub5);
    fbBuilder.putUint8(ub4);
    fbBuilder.putUint8(ub3);
    fbBuilder.putUint8(ub2);
    fbBuilder.putUint8(ub1);
    return fbBuilder.offset;
  }
}

class Ipv6ObjectBuilder extends fb.ObjectBuilder {
  final int _ub1;
  final int _ub2;
  final int _ub3;
  final int _ub4;
  final int _ub5;
  final int _ub6;
  final int _ub7;
  final int _ub8;
  final int _ub9;
  final int _ub10;
  final int _ub11;
  final int _ub12;
  final int _ub13;
  final int _ub14;
  final int _ub15;
  final int _ub16;

  Ipv6ObjectBuilder({
    required int ub1,
    required int ub2,
    required int ub3,
    required int ub4,
    required int ub5,
    required int ub6,
    required int ub7,
    required int ub8,
    required int ub9,
    required int ub10,
    required int ub11,
    required int ub12,
    required int ub13,
    required int ub14,
    required int ub15,
    required int ub16,
  }) : _ub1 = ub1,
       _ub2 = ub2,
       _ub3 = ub3,
       _ub4 = ub4,
       _ub5 = ub5,
       _ub6 = ub6,
       _ub7 = ub7,
       _ub8 = ub8,
       _ub9 = ub9,
       _ub10 = ub10,
       _ub11 = ub11,
       _ub12 = ub12,
       _ub13 = ub13,
       _ub14 = ub14,
       _ub15 = ub15,
       _ub16 = ub16;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    fbBuilder.putUint8(_ub16);
    fbBuilder.putUint8(_ub15);
    fbBuilder.putUint8(_ub14);
    fbBuilder.putUint8(_ub13);
    fbBuilder.putUint8(_ub12);
    fbBuilder.putUint8(_ub11);
    fbBuilder.putUint8(_ub10);
    fbBuilder.putUint8(_ub9);
    fbBuilder.putUint8(_ub8);
    fbBuilder.putUint8(_ub7);
    fbBuilder.putUint8(_ub6);
    fbBuilder.putUint8(_ub5);
    fbBuilder.putUint8(_ub4);
    fbBuilder.putUint8(_ub3);
    fbBuilder.putUint8(_ub2);
    fbBuilder.putUint8(_ub1);
    return fbBuilder.offset;
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}

class X25519Public {
  X25519Public._(this._bc, this._bcOffset);

  static const fb.Reader<X25519Public> reader = _X25519PublicReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  int get key1 => const fb.Uint64Reader().read(_bc, _bcOffset + 0);
  int get key2 => const fb.Uint64Reader().read(_bc, _bcOffset + 8);
  int get key3 => const fb.Uint64Reader().read(_bc, _bcOffset + 16);
  int get key4 => const fb.Uint64Reader().read(_bc, _bcOffset + 24);

  @override
  String toString() {
    return 'X25519Public{key1: ${key1}, key2: ${key2}, key3: ${key3}, key4: ${key4}}';
  }

  X25519PublicT unpack() => X25519PublicT(key1: key1, key2: key2, key3: key3, key4: key4);

  static int pack(fb.Builder fbBuilder, X25519PublicT? object) {
    if (object == null) return 0;
    return object.pack(fbBuilder);
  }
}

class X25519PublicT implements fb.Packable {
  int key1;
  int key2;
  int key3;
  int key4;

  X25519PublicT({required this.key1, required this.key2, required this.key3, required this.key4});

  @override
  int pack(fb.Builder fbBuilder) {
    fbBuilder.putUint64(key4);
    fbBuilder.putUint64(key3);
    fbBuilder.putUint64(key2);
    fbBuilder.putUint64(key1);
    return fbBuilder.offset;
  }

  @override
  String toString() {
    return 'X25519PublicT{key1: ${key1}, key2: ${key2}, key3: ${key3}, key4: ${key4}}';
  }
}

class _X25519PublicReader extends fb.StructReader<X25519Public> {
  const _X25519PublicReader();

  @override
  int get size => 32;

  @override
  X25519Public createObject(fb.BufferContext bc, int offset) => X25519Public._(bc, offset);
}

class X25519PublicBuilder {
  X25519PublicBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  int finish(int key1, int key2, int key3, int key4) {
    fbBuilder.putUint64(key4);
    fbBuilder.putUint64(key3);
    fbBuilder.putUint64(key2);
    fbBuilder.putUint64(key1);
    return fbBuilder.offset;
  }
}

class X25519PublicObjectBuilder extends fb.ObjectBuilder {
  final int _key1;
  final int _key2;
  final int _key3;
  final int _key4;

  X25519PublicObjectBuilder({required int key1, required int key2, required int key3, required int key4})
    : _key1 = key1,
      _key2 = key2,
      _key3 = key3,
      _key4 = key4;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    fbBuilder.putUint64(_key4);
    fbBuilder.putUint64(_key3);
    fbBuilder.putUint64(_key2);
    fbBuilder.putUint64(_key1);
    return fbBuilder.offset;
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}

class Uint128 {
  Uint128._(this._bc, this._bcOffset);

  static const fb.Reader<Uint128> reader = _Uint128Reader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  int get low => const fb.Uint64Reader().read(_bc, _bcOffset + 0);
  int get high => const fb.Uint64Reader().read(_bc, _bcOffset + 8);

  @override
  String toString() {
    return 'Uint128{low: ${low}, high: ${high}}';
  }

  Uint128T unpack() => Uint128T(low: low, high: high);

  static int pack(fb.Builder fbBuilder, Uint128T? object) {
    if (object == null) return 0;
    return object.pack(fbBuilder);
  }
}

class Uint128T implements fb.Packable {
  int low;
  int high;

  Uint128T({required this.low, required this.high});

  @override
  int pack(fb.Builder fbBuilder) {
    fbBuilder.putUint64(high);
    fbBuilder.putUint64(low);
    return fbBuilder.offset;
  }

  @override
  String toString() {
    return 'Uint128T{low: ${low}, high: ${high}}';
  }
}

class _Uint128Reader extends fb.StructReader<Uint128> {
  const _Uint128Reader();

  @override
  int get size => 16;

  @override
  Uint128 createObject(fb.BufferContext bc, int offset) => Uint128._(bc, offset);
}

class Uint128Builder {
  Uint128Builder(this.fbBuilder);

  final fb.Builder fbBuilder;

  int finish(int low, int high) {
    fbBuilder.putUint64(high);
    fbBuilder.putUint64(low);
    return fbBuilder.offset;
  }
}

class Uint128ObjectBuilder extends fb.ObjectBuilder {
  final int _low;
  final int _high;

  Uint128ObjectBuilder({required int low, required int high}) : _low = low, _high = high;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    fbBuilder.putUint64(_high);
    fbBuilder.putUint64(_low);
    return fbBuilder.offset;
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}

class PartnerId {
  PartnerId._(this._bc, this._bcOffset);

  static const fb.Reader<PartnerId> reader = _PartnerIdReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  int get low => const fb.Uint64Reader().read(_bc, _bcOffset + 0);
  int get high => const fb.Uint64Reader().read(_bc, _bcOffset + 8);

  @override
  String toString() {
    return 'PartnerId{low: ${low}, high: ${high}}';
  }

  PartnerIdT unpack() => PartnerIdT(low: low, high: high);

  static int pack(fb.Builder fbBuilder, PartnerIdT? object) {
    if (object == null) return 0;
    return object.pack(fbBuilder);
  }
}

class PartnerIdT implements fb.Packable {
  int low;
  int high;

  PartnerIdT({required this.low, required this.high});

  @override
  int pack(fb.Builder fbBuilder) {
    fbBuilder.putUint64(high);
    fbBuilder.putUint64(low);
    return fbBuilder.offset;
  }

  @override
  String toString() {
    return 'PartnerIdT{low: ${low}, high: ${high}}';
  }
}

class _PartnerIdReader extends fb.StructReader<PartnerId> {
  const _PartnerIdReader();

  @override
  int get size => 16;

  @override
  PartnerId createObject(fb.BufferContext bc, int offset) => PartnerId._(bc, offset);
}

class PartnerIdBuilder {
  PartnerIdBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  int finish(int low, int high) {
    fbBuilder.putUint64(high);
    fbBuilder.putUint64(low);
    return fbBuilder.offset;
  }
}

class PartnerIdObjectBuilder extends fb.ObjectBuilder {
  final int _low;
  final int _high;

  PartnerIdObjectBuilder({required int low, required int high}) : _low = low, _high = high;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    fbBuilder.putUint64(_high);
    fbBuilder.putUint64(_low);
    return fbBuilder.offset;
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}

class TerminalId {
  TerminalId._(this._bc, this._bcOffset);

  static const fb.Reader<TerminalId> reader = _TerminalIdReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  int get low => const fb.Uint64Reader().read(_bc, _bcOffset + 0);
  int get high => const fb.Uint64Reader().read(_bc, _bcOffset + 8);

  @override
  String toString() {
    return 'TerminalId{low: ${low}, high: ${high}}';
  }

  TerminalIdT unpack() => TerminalIdT(low: low, high: high);

  static int pack(fb.Builder fbBuilder, TerminalIdT? object) {
    if (object == null) return 0;
    return object.pack(fbBuilder);
  }
}

class TerminalIdT implements fb.Packable {
  int low;
  int high;

  TerminalIdT({required this.low, required this.high});

  @override
  int pack(fb.Builder fbBuilder) {
    fbBuilder.putUint64(high);
    fbBuilder.putUint64(low);
    return fbBuilder.offset;
  }

  @override
  String toString() {
    return 'TerminalIdT{low: ${low}, high: ${high}}';
  }
}

class _TerminalIdReader extends fb.StructReader<TerminalId> {
  const _TerminalIdReader();

  @override
  int get size => 16;

  @override
  TerminalId createObject(fb.BufferContext bc, int offset) => TerminalId._(bc, offset);
}

class TerminalIdBuilder {
  TerminalIdBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  int finish(int low, int high) {
    fbBuilder.putUint64(high);
    fbBuilder.putUint64(low);
    return fbBuilder.offset;
  }
}

class TerminalIdObjectBuilder extends fb.ObjectBuilder {
  final int _low;
  final int _high;

  TerminalIdObjectBuilder({required int low, required int high}) : _low = low, _high = high;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    fbBuilder.putUint64(_high);
    fbBuilder.putUint64(_low);
    return fbBuilder.offset;
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}

class Timestamp {
  Timestamp._(this._bc, this._bcOffset);

  static const fb.Reader<Timestamp> reader = _TimestampReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  int get ts => const fb.Int64Reader().read(_bc, _bcOffset + 0);

  @override
  String toString() {
    return 'Timestamp{ts: ${ts}}';
  }

  TimestampT unpack() => TimestampT(ts: ts);

  static int pack(fb.Builder fbBuilder, TimestampT? object) {
    if (object == null) return 0;
    return object.pack(fbBuilder);
  }
}

class TimestampT implements fb.Packable {
  int ts;

  TimestampT({required this.ts});

  @override
  int pack(fb.Builder fbBuilder) {
    fbBuilder.putInt64(ts);
    return fbBuilder.offset;
  }

  @override
  String toString() {
    return 'TimestampT{ts: ${ts}}';
  }
}

class _TimestampReader extends fb.StructReader<Timestamp> {
  const _TimestampReader();

  @override
  int get size => 8;

  @override
  Timestamp createObject(fb.BufferContext bc, int offset) => Timestamp._(bc, offset);
}

class TimestampBuilder {
  TimestampBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  int finish(int ts) {
    fbBuilder.putInt64(ts);
    return fbBuilder.offset;
  }
}

class TimestampObjectBuilder extends fb.ObjectBuilder {
  final int _ts;

  TimestampObjectBuilder({required int ts}) : _ts = ts;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    fbBuilder.putInt64(_ts);
    return fbBuilder.offset;
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}

class Frame {
  Frame._(this._bc, this._bcOffset);
  factory Frame(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<Frame> reader = _FrameReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  Header? get header => Header.reader.vTableGetNullable(_bc, _bcOffset, 4);
  List<int>? get bytes => const fb.Int8ListReader().vTableGetNullable(_bc, _bcOffset, 6);

  @override
  String toString() {
    return 'Frame{header: ${header}, bytes: ${bytes}}';
  }

  FrameT unpack() => FrameT(header: header?.unpack(), bytes: bytes?.toList());

  static int pack(fb.Builder fbBuilder, FrameT? object) {
    if (object == null) return 0;
    return object.pack(fbBuilder);
  }
}

class FrameT implements fb.Packable {
  HeaderT? header;
  List<int>? bytes;

  FrameT({this.header, this.bytes});

  @override
  int pack(fb.Builder fbBuilder) {
    final int? bytesOffset = bytes == null ? null : fbBuilder.writeListInt8(bytes!);
    fbBuilder.startTable(2);
    if (header != null) {
      fbBuilder.addStruct(0, header!.pack(fbBuilder));
    }
    fbBuilder.addOffset(1, bytesOffset);
    return fbBuilder.endTable();
  }

  @override
  String toString() {
    return 'FrameT{header: ${header}, bytes: ${bytes}}';
  }
}

class _FrameReader extends fb.TableReader<Frame> {
  const _FrameReader();

  @override
  Frame createObject(fb.BufferContext bc, int offset) => Frame._(bc, offset);
}

class FrameBuilder {
  FrameBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(2);
  }

  int addHeader(int offset) {
    fbBuilder.addStruct(0, offset);
    return fbBuilder.offset;
  }

  int addBytesOffset(int? offset) {
    fbBuilder.addOffset(1, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class FrameObjectBuilder extends fb.ObjectBuilder {
  final HeaderObjectBuilder? _header;
  final List<int>? _bytes;

  FrameObjectBuilder({HeaderObjectBuilder? header, List<int>? bytes}) : _header = header, _bytes = bytes;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? bytesOffset = _bytes == null ? null : fbBuilder.writeListInt8(_bytes!);
    fbBuilder.startTable(2);
    if (_header != null) {
      fbBuilder.addStruct(0, _header!.finish(fbBuilder));
    }
    fbBuilder.addOffset(1, bytesOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}

class Header {
  Header._(this._bc, this._bcOffset);

  static const fb.Reader<Header> reader = _HeaderReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  int get len => const fb.Uint32Reader().read(_bc, _bcOffset + 0);
  int get headerType => const fb.Uint32Reader().read(_bc, _bcOffset + 4);
  int get frameType => const fb.Uint32Reader().read(_bc, _bcOffset + 8);
  TerminalId get toTerminalId => TerminalId.reader.read(_bc, _bcOffset + 16);
  X25519Public get key => X25519Public.reader.read(_bc, _bcOffset + 32);

  @override
  String toString() {
    return 'Header{len: ${len}, headerType: ${headerType}, frameType: ${frameType}, toTerminalId: ${toTerminalId}, key: ${key}}';
  }

  HeaderT unpack() => HeaderT(len: len, headerType: headerType, frameType: frameType, toTerminalId: toTerminalId.unpack(), key: key.unpack());

  static int pack(fb.Builder fbBuilder, HeaderT? object) {
    if (object == null) return 0;
    return object.pack(fbBuilder);
  }
}

class HeaderT implements fb.Packable {
  int len;
  int headerType;
  int frameType;
  TerminalIdT toTerminalId;
  X25519PublicT key;

  HeaderT({required this.len, required this.headerType, required this.frameType, required this.toTerminalId, required this.key});

  @override
  int pack(fb.Builder fbBuilder) {
    key.pack(fbBuilder);
    toTerminalId.pack(fbBuilder);
    fbBuilder.pad(4);
    fbBuilder.putUint32(frameType);
    fbBuilder.putUint32(headerType);
    fbBuilder.putUint32(len);
    return fbBuilder.offset;
  }

  @override
  String toString() {
    return 'HeaderT{len: ${len}, headerType: ${headerType}, frameType: ${frameType}, toTerminalId: ${toTerminalId}, key: ${key}}';
  }
}

class _HeaderReader extends fb.StructReader<Header> {
  const _HeaderReader();

  @override
  int get size => 64;

  @override
  Header createObject(fb.BufferContext bc, int offset) => Header._(bc, offset);
}

class HeaderBuilder {
  HeaderBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  int finish(int len, int headerType, int frameType, fb.StructBuilder toTerminalId, fb.StructBuilder key) {
    key();
    toTerminalId();
    fbBuilder.pad(4);
    fbBuilder.putUint32(frameType);
    fbBuilder.putUint32(headerType);
    fbBuilder.putUint32(len);
    return fbBuilder.offset;
  }
}

class HeaderObjectBuilder extends fb.ObjectBuilder {
  final int _len;
  final int _headerType;
  final int _frameType;
  final TerminalIdObjectBuilder _toTerminalId;
  final X25519PublicObjectBuilder _key;

  HeaderObjectBuilder({
    required int len,
    required int headerType,
    required int frameType,
    required TerminalIdObjectBuilder toTerminalId,
    required X25519PublicObjectBuilder key,
  }) : _len = len,
       _headerType = headerType,
       _frameType = frameType,
       _toTerminalId = toTerminalId,
       _key = key;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    _key.finish(fbBuilder);
    _toTerminalId.finish(fbBuilder);
    fbBuilder.pad(4);
    fbBuilder.putUint32(_frameType);
    fbBuilder.putUint32(_headerType);
    fbBuilder.putUint32(_len);
    return fbBuilder.offset;
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}

class FrameConfirm {
  FrameConfirm._(this._bc, this._bcOffset);

  static const fb.Reader<FrameConfirm> reader = _FrameConfirmReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  UlidBytes get id => UlidBytes.reader.read(_bc, _bcOffset + 0);
  UlidBytes get frameId => UlidBytes.reader.read(_bc, _bcOffset + 16);

  @override
  String toString() {
    return 'FrameConfirm{id: ${id}, frameId: ${frameId}}';
  }

  FrameConfirmT unpack() => FrameConfirmT(id: id.unpack(), frameId: frameId.unpack());

  static int pack(fb.Builder fbBuilder, FrameConfirmT? object) {
    if (object == null) return 0;
    return object.pack(fbBuilder);
  }
}

class FrameConfirmT implements fb.Packable {
  UlidBytesT id;
  UlidBytesT frameId;

  FrameConfirmT({required this.id, required this.frameId});

  @override
  int pack(fb.Builder fbBuilder) {
    frameId.pack(fbBuilder);
    id.pack(fbBuilder);
    return fbBuilder.offset;
  }

  @override
  String toString() {
    return 'FrameConfirmT{id: ${id}, frameId: ${frameId}}';
  }
}

class _FrameConfirmReader extends fb.StructReader<FrameConfirm> {
  const _FrameConfirmReader();

  @override
  int get size => 32;

  @override
  FrameConfirm createObject(fb.BufferContext bc, int offset) => FrameConfirm._(bc, offset);
}

class FrameConfirmBuilder {
  FrameConfirmBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  int finish(fb.StructBuilder id, fb.StructBuilder frameId) {
    frameId();
    id();
    return fbBuilder.offset;
  }
}

class FrameConfirmObjectBuilder extends fb.ObjectBuilder {
  final UlidBytesObjectBuilder _id;
  final UlidBytesObjectBuilder _frameId;

  FrameConfirmObjectBuilder({required UlidBytesObjectBuilder id, required UlidBytesObjectBuilder frameId}) : _id = id, _frameId = frameId;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    _frameId.finish(fbBuilder);
    _id.finish(fbBuilder);
    return fbBuilder.offset;
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}

class ErrorInfo {
  ErrorInfo._(this._bc, this._bcOffset);
  factory ErrorInfo(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<ErrorInfo> reader = _ErrorInfoReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  UlidBytes? get id => UlidBytes.reader.vTableGetNullable(_bc, _bcOffset, 4);
  UlidBytes? get reqId => UlidBytes.reader.vTableGetNullable(_bc, _bcOffset, 6);
  int get code => const fb.Uint32Reader().vTableGet(_bc, _bcOffset, 8, 0);
  String? get message => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 10);

  @override
  String toString() {
    return 'ErrorInfo{id: ${id}, reqId: ${reqId}, code: ${code}, message: ${message}}';
  }

  ErrorInfoT unpack() => ErrorInfoT(id: id?.unpack(), reqId: reqId?.unpack(), code: code, message: message);

  static int pack(fb.Builder fbBuilder, ErrorInfoT? object) {
    if (object == null) return 0;
    return object.pack(fbBuilder);
  }
}

class ErrorInfoT implements fb.Packable {
  UlidBytesT? id;
  UlidBytesT? reqId;
  int code;
  String? message;

  ErrorInfoT({this.id, this.reqId, this.code = 0, this.message});

  @override
  int pack(fb.Builder fbBuilder) {
    final int? messageOffset = message == null ? null : fbBuilder.writeString(message!);
    fbBuilder.startTable(4);
    if (id != null) {
      fbBuilder.addStruct(0, id!.pack(fbBuilder));
    }
    if (reqId != null) {
      fbBuilder.addStruct(1, reqId!.pack(fbBuilder));
    }
    fbBuilder.addUint32(2, code);
    fbBuilder.addOffset(3, messageOffset);
    return fbBuilder.endTable();
  }

  @override
  String toString() {
    return 'ErrorInfoT{id: ${id}, reqId: ${reqId}, code: ${code}, message: ${message}}';
  }
}

class _ErrorInfoReader extends fb.TableReader<ErrorInfo> {
  const _ErrorInfoReader();

  @override
  ErrorInfo createObject(fb.BufferContext bc, int offset) => ErrorInfo._(bc, offset);
}

class ErrorInfoBuilder {
  ErrorInfoBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(4);
  }

  int addId(int offset) {
    fbBuilder.addStruct(0, offset);
    return fbBuilder.offset;
  }

  int addReqId(int offset) {
    fbBuilder.addStruct(1, offset);
    return fbBuilder.offset;
  }

  int addCode(int? code) {
    fbBuilder.addUint32(2, code);
    return fbBuilder.offset;
  }

  int addMessageOffset(int? offset) {
    fbBuilder.addOffset(3, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class ErrorInfoObjectBuilder extends fb.ObjectBuilder {
  final UlidBytesObjectBuilder? _id;
  final UlidBytesObjectBuilder? _reqId;
  final int? _code;
  final String? _message;

  ErrorInfoObjectBuilder({UlidBytesObjectBuilder? id, UlidBytesObjectBuilder? reqId, int? code, String? message})
    : _id = id,
      _reqId = reqId,
      _code = code,
      _message = message;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? messageOffset = _message == null ? null : fbBuilder.writeString(_message!);
    fbBuilder.startTable(4);
    if (_id != null) {
      fbBuilder.addStruct(0, _id!.finish(fbBuilder));
    }
    if (_reqId != null) {
      fbBuilder.addStruct(1, _reqId!.finish(fbBuilder));
    }
    fbBuilder.addUint32(2, _code);
    fbBuilder.addOffset(3, messageOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}

class FrameError {
  FrameError._(this._bc, this._bcOffset);
  factory FrameError(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<FrameError> reader = _FrameErrorReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  Header? get header => Header.reader.vTableGetNullable(_bc, _bcOffset, 4);
  ErrorInfo? get errorInfo => ErrorInfo.reader.vTableGetNullable(_bc, _bcOffset, 6);

  @override
  String toString() {
    return 'FrameError{header: ${header}, errorInfo: ${errorInfo}}';
  }

  FrameErrorT unpack() => FrameErrorT(header: header?.unpack(), errorInfo: errorInfo?.unpack());

  static int pack(fb.Builder fbBuilder, FrameErrorT? object) {
    if (object == null) return 0;
    return object.pack(fbBuilder);
  }
}

class FrameErrorT implements fb.Packable {
  HeaderT? header;
  ErrorInfoT? errorInfo;

  FrameErrorT({this.header, this.errorInfo});

  @override
  int pack(fb.Builder fbBuilder) {
    final int? errorInfoOffset = errorInfo?.pack(fbBuilder);
    fbBuilder.startTable(2);
    if (header != null) {
      fbBuilder.addStruct(0, header!.pack(fbBuilder));
    }
    fbBuilder.addOffset(1, errorInfoOffset);
    return fbBuilder.endTable();
  }

  @override
  String toString() {
    return 'FrameErrorT{header: ${header}, errorInfo: ${errorInfo}}';
  }
}

class _FrameErrorReader extends fb.TableReader<FrameError> {
  const _FrameErrorReader();

  @override
  FrameError createObject(fb.BufferContext bc, int offset) => FrameError._(bc, offset);
}

class FrameErrorBuilder {
  FrameErrorBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(2);
  }

  int addHeader(int offset) {
    fbBuilder.addStruct(0, offset);
    return fbBuilder.offset;
  }

  int addErrorInfoOffset(int? offset) {
    fbBuilder.addOffset(1, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class FrameErrorObjectBuilder extends fb.ObjectBuilder {
  final HeaderObjectBuilder? _header;
  final ErrorInfoObjectBuilder? _errorInfo;

  FrameErrorObjectBuilder({HeaderObjectBuilder? header, ErrorInfoObjectBuilder? errorInfo}) : _header = header, _errorInfo = errorInfo;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? errorInfoOffset = _errorInfo?.getOrCreateOffset(fbBuilder);
    fbBuilder.startTable(2);
    if (_header != null) {
      fbBuilder.addStruct(0, _header!.finish(fbBuilder));
    }
    fbBuilder.addOffset(1, errorInfoOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
