// automatically generated by the FlatBuffers compiler, do not modify
// ignore_for_file: unused_import, unused_field, unused_element, unused_local_variable, constant_identifier_names

library net_discovery;

import 'dart:typed_data' show Uint8List;
import 'package:flat_buffers/flat_buffers.dart' as fb;

import './base_base_generated.dart' as base;

class DnsTerminal {
  DnsTerminal._(this._bc, this._bcOffset);
  factory DnsTerminal(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<DnsTerminal> reader = _DnsTerminalReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  base.UlidBytes? get id => base.UlidBytes.reader.vTableGetNullable(_bc, _bcOffset, 4);
  base.PartnerId? get parterId => base.PartnerId.reader.vTableGetNullable(_bc, _bcOffset, 6);
  base.TerminalId? get terminalId => base.TerminalId.reader.vTableGetNullable(_bc, _bcOffset, 8);
  String? get hostName => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 10);
  int get ipV4 => const fb.Uint32Reader().vTableGet(_bc, _bcOffset, 12, 0);
  int get portV4 => const fb.Uint16Reader().vTableGet(_bc, _bcOffset, 14, 0);
  int get ipV6 => const fb.Uint64Reader().vTableGet(_bc, _bcOffset, 16, 0);
  int get portV6 => const fb.Uint16Reader().vTableGet(_bc, _bcOffset, 18, 0);

  @override
  String toString() {
    return 'DnsTerminal{id: ${id}, parterId: ${parterId}, terminalId: ${terminalId}, hostName: ${hostName}, ipV4: ${ipV4}, portV4: ${portV4}, ipV6: ${ipV6}, portV6: ${portV6}}';
  }
}

class _DnsTerminalReader extends fb.TableReader<DnsTerminal> {
  const _DnsTerminalReader();

  @override
  DnsTerminal createObject(fb.BufferContext bc, int offset) => DnsTerminal._(bc, offset);
}

class DnsTerminalBuilder {
  DnsTerminalBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(8);
  }

  int addId(int offset) {
    fbBuilder.addStruct(0, offset);
    return fbBuilder.offset;
  }

  int addParterId(int offset) {
    fbBuilder.addStruct(1, offset);
    return fbBuilder.offset;
  }

  int addTerminalId(int offset) {
    fbBuilder.addStruct(2, offset);
    return fbBuilder.offset;
  }

  int addHostNameOffset(int? offset) {
    fbBuilder.addOffset(3, offset);
    return fbBuilder.offset;
  }

  int addIpV4(int? ipV4) {
    fbBuilder.addUint32(4, ipV4);
    return fbBuilder.offset;
  }

  int addPortV4(int? portV4) {
    fbBuilder.addUint16(5, portV4);
    return fbBuilder.offset;
  }

  int addIpV6(int? ipV6) {
    fbBuilder.addUint64(6, ipV6);
    return fbBuilder.offset;
  }

  int addPortV6(int? portV6) {
    fbBuilder.addUint16(7, portV6);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class DnsTerminalObjectBuilder extends fb.ObjectBuilder {
  final base.UlidBytesObjectBuilder? _id;
  final base.PartnerIdObjectBuilder? _parterId;
  final base.TerminalIdObjectBuilder? _terminalId;
  final String? _hostName;
  final int? _ipV4;
  final int? _portV4;
  final int? _ipV6;
  final int? _portV6;

  DnsTerminalObjectBuilder({
    base.UlidBytesObjectBuilder? id,
    base.PartnerIdObjectBuilder? parterId,
    base.TerminalIdObjectBuilder? terminalId,
    String? hostName,
    int? ipV4,
    int? portV4,
    int? ipV6,
    int? portV6,
  }) : _id = id,
       _parterId = parterId,
       _terminalId = terminalId,
       _hostName = hostName,
       _ipV4 = ipV4,
       _portV4 = portV4,
       _ipV6 = ipV6,
       _portV6 = portV6;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? hostNameOffset = _hostName == null ? null : fbBuilder.writeString(_hostName!);
    fbBuilder.startTable(8);
    if (_id != null) {
      fbBuilder.addStruct(0, _id!.finish(fbBuilder));
    }
    if (_parterId != null) {
      fbBuilder.addStruct(1, _parterId!.finish(fbBuilder));
    }
    if (_terminalId != null) {
      fbBuilder.addStruct(2, _terminalId!.finish(fbBuilder));
    }
    fbBuilder.addOffset(3, hostNameOffset);
    fbBuilder.addUint32(4, _ipV4);
    fbBuilder.addUint16(5, _portV4);
    fbBuilder.addUint64(6, _ipV6);
    fbBuilder.addUint16(7, _portV6);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}

class Hi {
  Hi._(this._bc, this._bcOffset);
  factory Hi(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<Hi> reader = _HiReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  base.UlidBytes? get id => base.UlidBytes.reader.vTableGetNullable(_bc, _bcOffset, 4);
  DnsTerminal? get dnsPartner => DnsTerminal.reader.vTableGetNullable(_bc, _bcOffset, 6);

  @override
  String toString() {
    return 'Hi{id: ${id}, dnsPartner: ${dnsPartner}}';
  }
}

class _HiReader extends fb.TableReader<Hi> {
  const _HiReader();

  @override
  Hi createObject(fb.BufferContext bc, int offset) => Hi._(bc, offset);
}

class HiBuilder {
  HiBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(2);
  }

  int addId(int offset) {
    fbBuilder.addStruct(0, offset);
    return fbBuilder.offset;
  }

  int addDnsPartnerOffset(int? offset) {
    fbBuilder.addOffset(1, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class HiObjectBuilder extends fb.ObjectBuilder {
  final base.UlidBytesObjectBuilder? _id;
  final DnsTerminalObjectBuilder? _dnsPartner;

  HiObjectBuilder({base.UlidBytesObjectBuilder? id, DnsTerminalObjectBuilder? dnsPartner}) : _id = id, _dnsPartner = dnsPartner;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? dnsPartnerOffset = _dnsPartner?.getOrCreateOffset(fbBuilder);
    fbBuilder.startTable(2);
    if (_id != null) {
      fbBuilder.addStruct(0, _id!.finish(fbBuilder));
    }
    fbBuilder.addOffset(1, dnsPartnerOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}

class DsnPartners {
  DsnPartners._(this._bc, this._bcOffset);
  factory DsnPartners(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<DsnPartners> reader = _DsnPartnersReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  base.UlidBytes? get id => base.UlidBytes.reader.vTableGetNullable(_bc, _bcOffset, 4);
  List<DnsTerminal>? get dnsPartners => const fb.ListReader<DnsTerminal>(DnsTerminal.reader).vTableGetNullable(_bc, _bcOffset, 6);

  @override
  String toString() {
    return 'DsnPartners{id: ${id}, dnsPartners: ${dnsPartners}}';
  }
}

class _DsnPartnersReader extends fb.TableReader<DsnPartners> {
  const _DsnPartnersReader();

  @override
  DsnPartners createObject(fb.BufferContext bc, int offset) => DsnPartners._(bc, offset);
}

class DsnPartnersBuilder {
  DsnPartnersBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(2);
  }

  int addId(int offset) {
    fbBuilder.addStruct(0, offset);
    return fbBuilder.offset;
  }

  int addDnsPartnersOffset(int? offset) {
    fbBuilder.addOffset(1, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class DsnPartnersObjectBuilder extends fb.ObjectBuilder {
  final base.UlidBytesObjectBuilder? _id;
  final List<DnsTerminalObjectBuilder>? _dnsPartners;

  DsnPartnersObjectBuilder({base.UlidBytesObjectBuilder? id, List<DnsTerminalObjectBuilder>? dnsPartners}) : _id = id, _dnsPartners = dnsPartners;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? dnsPartnersOffset = _dnsPartners == null ? null : fbBuilder.writeList(_dnsPartners!.map((b) => b.getOrCreateOffset(fbBuilder)).toList());
    fbBuilder.startTable(2);
    if (_id != null) {
      fbBuilder.addStruct(0, _id!.finish(fbBuilder));
    }
    fbBuilder.addOffset(1, dnsPartnersOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}

class QueryPartners {
  QueryPartners._(this._bc, this._bcOffset);
  factory QueryPartners(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<QueryPartners> reader = _QueryPartnersReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  base.UlidBytes? get id => base.UlidBytes.reader.vTableGetNullable(_bc, _bcOffset, 4);
  DnsTerminal? get dnsPartner => DnsTerminal.reader.vTableGetNullable(_bc, _bcOffset, 6);

  @override
  String toString() {
    return 'QueryPartners{id: ${id}, dnsPartner: ${dnsPartner}}';
  }
}

class _QueryPartnersReader extends fb.TableReader<QueryPartners> {
  const _QueryPartnersReader();

  @override
  QueryPartners createObject(fb.BufferContext bc, int offset) => QueryPartners._(bc, offset);
}

class QueryPartnersBuilder {
  QueryPartnersBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(2);
  }

  int addId(int offset) {
    fbBuilder.addStruct(0, offset);
    return fbBuilder.offset;
  }

  int addDnsPartnerOffset(int? offset) {
    fbBuilder.addOffset(1, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class QueryPartnersObjectBuilder extends fb.ObjectBuilder {
  final base.UlidBytesObjectBuilder? _id;
  final DnsTerminalObjectBuilder? _dnsPartner;

  QueryPartnersObjectBuilder({base.UlidBytesObjectBuilder? id, DnsTerminalObjectBuilder? dnsPartner}) : _id = id, _dnsPartner = dnsPartner;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? dnsPartnerOffset = _dnsPartner?.getOrCreateOffset(fbBuilder);
    fbBuilder.startTable(2);
    if (_id != null) {
      fbBuilder.addStruct(0, _id!.finish(fbBuilder));
    }
    fbBuilder.addOffset(1, dnsPartnerOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
