// automatically generated by the FlatBuffers compiler, do not modify

package base

@Suppress("unused")
class FrameType private constructor() {
    companion object {
        const val Message: Short = 0
        const val MessageAck: Short = 1
        const val OnLine: Short = 100
        const val OnLineAck: Short = 101
    }
}
