// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package net_discovery

import (
	flatbuffers "github.com/google/flatbuffers/go"

	base "github.com/peacess/doors/doors_lib/go/idl/base"
)

type QueryPartnersInT struct {
	Id       *base.UlidBytesT `json:"id"`
	Terminal *DnsTerminalT    `json:"terminal"`
}

func (t *QueryPartnersInT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	terminalOffset := t.Terminal.Pack(builder)
	QueryPartnersInStart(builder)
	idOffset := t.Id.Pack(builder)
	QueryPartnersInAddId(builder, idOffset)
	QueryPartnersInAddTerminal(builder, terminalOffset)
	return QueryPartnersInEnd(builder)
}

func (rcv *QueryPartnersIn) UnPackTo(t *QueryPartnersInT) {
	t.Id = rcv.Id(nil).UnPack()
	t.Terminal = rcv.Terminal(nil).UnPack()
}

func (rcv *QueryPartnersIn) UnPack() *QueryPartnersInT {
	if rcv == nil {
		return nil
	}
	t := &QueryPartnersInT{}
	rcv.UnPackTo(t)
	return t
}

type QueryPartnersIn struct {
	_tab flatbuffers.Table
}

func GetRootAsQueryPartnersIn(buf []byte, offset flatbuffers.UOffsetT) *QueryPartnersIn {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &QueryPartnersIn{}
	x.Init(buf, n+offset)
	return x
}

func FinishQueryPartnersInBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsQueryPartnersIn(buf []byte, offset flatbuffers.UOffsetT) *QueryPartnersIn {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &QueryPartnersIn{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedQueryPartnersInBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *QueryPartnersIn) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *QueryPartnersIn) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *QueryPartnersIn) Id(obj *base.UlidBytes) *base.UlidBytes {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := o + rcv._tab.Pos
		if obj == nil {
			obj = new(base.UlidBytes)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *QueryPartnersIn) Terminal(obj *DnsTerminal) *DnsTerminal {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(DnsTerminal)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func QueryPartnersInStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func QueryPartnersInAddId(builder *flatbuffers.Builder, id flatbuffers.UOffsetT) {
	builder.PrependStructSlot(0, flatbuffers.UOffsetT(id), 0)
}
func QueryPartnersInAddTerminal(builder *flatbuffers.Builder, terminal flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(terminal), 0)
}
func QueryPartnersInEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
