// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package net_discovery

import (
	flatbuffers "github.com/google/flatbuffers/go"

	base "github.com/peacess/doors/doors_lib/go/idl/base"
)

type Regestry struct {
	_tab flatbuffers.Table
}

func GetRootAsRegestry(buf []byte, offset flatbuffers.UOffsetT) *Regestry {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Regestry{}
	x.Init(buf, n+offset)
	return x
}

func FinishRegestryBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsRegestry(buf []byte, offset flatbuffers.UOffsetT) *Regestry {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Regestry{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedRegestryBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Regestry) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Regestry) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Regestry) ParterId(obj *base.PartnerId) *base.PartnerId {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := o + rcv._tab.Pos
		if obj == nil {
			obj = new(base.PartnerId)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func RegestryStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func RegestryAddParterId(builder *flatbuffers.Builder, parterId flatbuffers.UOffsetT) {
	builder.PrependStructSlot(0, flatbuffers.UOffsetT(parterId), 0)
}
func RegestryEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
