// automatically generated by the FlatBuffers compiler, do not modify

package netDataType

import com.google.flatbuffers.kotlin.*
import kotlin.jvm.JvmInline
@Suppress("unused")
@JvmInline
value class HeaderType (val value: UInt) {
    companion object {
        val None = HeaderType(0u)
        val NetDiscovery = HeaderType(1u)
        val Chat = HeaderType(2u)
        val FfiRpc = HeaderType(3u)
        val names : Array<String> = arrayOf("none", "net_discovery", "chat", "ffi_rpc")
        @JvmStatic
        fun name(e: HeaderType) : String = names[e.value.toInt()]
    }
}

typealias HeaderTypeArray = UIntArray
