// automatically generated by the FlatBuffers compiler, do not modify

package net_discovery

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class QueryDnsTerminalIn : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : QueryDnsTerminalIn {
        __init(_i, _bb)
        return this
    }
    val id : base.UlidBytes? get() = id(base.UlidBytes())
    fun id(obj: base.UlidBytes) : base.UlidBytes? {
        val o = __offset(4)
        return if (o != 0) {
            obj.__assign(o + bb_pos, bb)
        } else {
            null
        }
    }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsQueryDnsTerminalIn(_bb: ByteBuffer): QueryDnsTerminalIn = getRootAsQueryDnsTerminalIn(_bb, QueryDnsTerminalIn())
        fun getRootAsQueryDnsTerminalIn(_bb: ByteBuffer, obj: QueryDnsTerminalIn): QueryDnsTerminalIn {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun startQueryDnsTerminalIn(builder: FlatBufferBuilder) = builder.startTable(1)
        fun addId(builder: FlatBufferBuilder, id: Int) = builder.addStruct(0, id, 0)
        fun endQueryDnsTerminalIn(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
