// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package base

import "strconv"

type HeaderType uint32

const (
	HeaderTypenone          HeaderType = 0
	HeaderTypenet_discovery HeaderType = 1
	HeaderTypechat          HeaderType = 2
	HeaderTypeffi_rpc       HeaderType = 3
	HeaderTypeerror_info    HeaderType = 2147483647
)

var EnumNamesHeaderType = map[HeaderType]string{
	HeaderTypenone:          "none",
	HeaderTypenet_discovery: "net_discovery",
	HeaderTypechat:          "chat",
	HeaderTypeffi_rpc:       "ffi_rpc",
	HeaderTypeerror_info:    "error_info",
}

var EnumValuesHeaderType = map[string]HeaderType{
	"none":          HeaderTypenone,
	"net_discovery": HeaderTypenet_discovery,
	"chat":          HeaderTypechat,
	"ffi_rpc":       HeaderTypeffi_rpc,
	"error_info":    HeaderTypeerror_info,
}

func (v HeaderType) String() string {
	if s, ok := EnumNamesHeaderType[v]; ok {
		return s
	}
	return "HeaderType(" + strconv.FormatInt(int64(v), 10) + ")"
}
