// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package chat

import "strconv"

type ChatType uint32

const (
	ChatTypenone             ChatType = 0
	ChatTypetext_message     ChatType = 1
	ChatTypetext_message_ack ChatType = 2
)

var EnumNamesChatType = map[ChatType]string{
	ChatTypenone:             "none",
	ChatTypetext_message:     "text_message",
	ChatTypetext_message_ack: "text_message_ack",
}

var EnumValuesChatType = map[string]ChatType{
	"none":             ChatTypenone,
	"text_message":     ChatTypetext_message,
	"text_message_ack": ChatTypetext_message_ack,
}

func (v ChatType) String() string {
	if s, ok := EnumNamesChatType[v]; ok {
		return s
	}
	return "ChatType(" + strconv.FormatInt(int64(v), 10) + ")"
}
