// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package chat

import (
	flatbuffers "github.com/google/flatbuffers/go"

	base "github.com/peacess/doors/doors_lib/go/idl/base"
)

type TextMessageRpc struct {
	_tab flatbuffers.Table
}

func GetRootAsTextMessageRpc(buf []byte, offset flatbuffers.UOffsetT) *TextMessageRpc {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TextMessageRpc{}
	x.Init(buf, n+offset)
	return x
}

func FinishTextMessageRpcBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsTextMessageRpc(buf []byte, offset flatbuffers.UOffsetT) *TextMessageRpc {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &TextMessageRpc{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedTextMessageRpcBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *TextMessageRpc) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TextMessageRpc) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *TextMessageRpc) Id(obj *base.UlidBytes) *base.UlidBytes {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := o + rcv._tab.Pos
		if obj == nil {
			obj = new(base.UlidBytes)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *TextMessageRpc) TextMessage(obj *TextMessage) *TextMessage {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(TextMessage)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func TextMessageRpcStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func TextMessageRpcAddId(builder *flatbuffers.Builder, id flatbuffers.UOffsetT) {
	builder.PrependStructSlot(0, flatbuffers.UOffsetT(id), 0)
}
func TextMessageRpcAddTextMessage(builder *flatbuffers.Builder, textMessage flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(textMessage), 0)
}
func TextMessageRpcEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
