// automatically generated by the FlatBuffers compiler, do not modify

package netDiscovery

import com.google.flatbuffers.kotlin.*
import kotlin.jvm.JvmInline
@Suppress("unused")
class MySelf : Struct() {

    fun init(i: Int, buffer: ReadWriteBuffer) : MySelf = reset(i, buffer)

    val id : base.UlidBytes? get() = id(base.UlidBytes())
    fun id(obj: base.UlidBytes) : base.UlidBytes? = obj.init(bufferPos + 0, bb)

    companion object {

        @JvmStatic
        fun createMySelf(builder: FlatBufferBuilder, id_low: ULong, id_high: ULong) : Offset<MySelf> {
            builder.prep(8, 16)
            builder.prep(8, 16)
            builder.put(id_high)
            builder.put(id_low)
            return Offset(builder.offset())
        }
    }
}

typealias MySelfOffsetArray = OffsetArray<MySelf>

inline fun MySelfOffsetArray(size: Int, crossinline call: (Int) -> Offset<MySelf>): MySelfOffsetArray =
    MySelfOffsetArray(IntArray(size) { call(it).value })
