// automatically generated by the FlatBuffers compiler, do not modify

package ffiData

import com.google.flatbuffers.kotlin.*
import kotlin.jvm.JvmInline
@Suppress("unused")
@JvmInline
value class FfiRpcDiscoveryType (val value: UInt) {
    companion object {
        val None = FfiRpcDiscoveryType(0u)
        val PartnerSelfIn = FfiRpcDiscoveryType(1u)
        val PartnerSelfOut = FfiRpcDiscoveryType(2u)
        val names : Array<String> = arrayOf("none", "partner_self_in", "partner_self_out")
        @JvmStatic
        fun name(e: FfiRpcDiscoveryType) : String = names[e.value.toInt()]
    }
}

typealias FfiRpcDiscoveryTypeArray = UIntArray
