// automatically generated by the FlatBuffers compiler, do not modify

package ffiData

import com.google.flatbuffers.kotlin.*
import kotlin.jvm.JvmInline
@Suppress("unused")
class FfiRpcPartnerSelfOut : Table() {

    fun init(i: Int, buffer: ReadWriteBuffer) : FfiRpcPartnerSelfOut = reset(i, buffer)

    val header : base.Header? get() = header(base.Header())
    fun header(obj: base.Header) : base.Header? = lookupField(4, null ) { obj.init(it + bufferPos, bb) }

    val message : ffiData.PartnerSelfOut? get() = message(ffiData.PartnerSelfOut())
    fun message(obj: ffiData.PartnerSelfOut) : ffiData.PartnerSelfOut? = lookupField(6, null ) { obj.init(indirect(it + bufferPos), bb) }

    companion object {
        @JvmStatic
        fun validateVersion() = VERSION_2_0_8

        @JvmStatic
        fun asRoot(buffer: ReadWriteBuffer) : FfiRpcPartnerSelfOut = asRoot(buffer, FfiRpcPartnerSelfOut())
        @JvmStatic
        fun asRoot(buffer: ReadWriteBuffer, obj: FfiRpcPartnerSelfOut) : FfiRpcPartnerSelfOut = obj.init(buffer.getInt(buffer.limit) + buffer.limit, buffer)


        @JvmStatic
        fun startFfiRpcPartnerSelfOut(builder: FlatBufferBuilder) = builder.startTable(2)

        @JvmStatic
        fun addHeader(builder: FlatBufferBuilder, header: Offset<base.Header>) = builder.addStruct(0, header.value, 0)

        @JvmStatic
        fun addMessage(builder: FlatBufferBuilder, message: Offset<ffiData.PartnerSelfOut>) = builder.add(1, message, 0)

        @JvmStatic
        fun endFfiRpcPartnerSelfOut(builder: FlatBufferBuilder) : Offset<FfiRpcPartnerSelfOut> {
            val o: Offset<FfiRpcPartnerSelfOut> = builder.endTable()
            return o
        }
    }
}

typealias FfiRpcPartnerSelfOutOffsetArray = OffsetArray<FfiRpcPartnerSelfOut>

inline fun FfiRpcPartnerSelfOutOffsetArray(size: Int, crossinline call: (Int) -> Offset<FfiRpcPartnerSelfOut>): FfiRpcPartnerSelfOutOffsetArray =
    FfiRpcPartnerSelfOutOffsetArray(IntArray(size) { call(it).value })
