// automatically generated by the FlatBuffers compiler, do not modify

package ffiData

import com.google.flatbuffers.kotlin.*
import kotlin.jvm.JvmInline
@Suppress("unused")
class PartnerSelfOut : Table() {

    fun init(i: Int, buffer: ReadWriteBuffer) : PartnerSelfOut = reset(i, buffer)

    val id : base.UlidBytes? get() = id(base.UlidBytes())
    fun id(obj: base.UlidBytes) : base.UlidBytes? = lookupField(4, null ) { obj.init(it + bufferPos, bb) }

    val terminal : netDiscovery.DnsTerminal? get() = terminal(netDiscovery.DnsTerminal())
    fun terminal(obj: netDiscovery.DnsTerminal) : netDiscovery.DnsTerminal? = lookupField(6, null ) { obj.init(indirect(it + bufferPos), bb) }

    companion object {
        @JvmStatic
        fun validateVersion() = VERSION_2_0_8

        @JvmStatic
        fun asRoot(buffer: ReadWriteBuffer) : PartnerSelfOut = asRoot(buffer, PartnerSelfOut())
        @JvmStatic
        fun asRoot(buffer: ReadWriteBuffer, obj: PartnerSelfOut) : PartnerSelfOut = obj.init(buffer.getInt(buffer.limit) + buffer.limit, buffer)


        @JvmStatic
        fun startPartnerSelfOut(builder: FlatBufferBuilder) = builder.startTable(2)

        @JvmStatic
        fun addId(builder: FlatBufferBuilder, id: Offset<base.UlidBytes>) = builder.addStruct(0, id.value, 0)

        @JvmStatic
        fun addTerminal(builder: FlatBufferBuilder, terminal: Offset<netDiscovery.DnsTerminal>) = builder.add(1, terminal, 0)

        @JvmStatic
        fun endPartnerSelfOut(builder: FlatBufferBuilder) : Offset<PartnerSelfOut> {
            val o: Offset<PartnerSelfOut> = builder.endTable()
            return o
        }
    }
}

typealias PartnerSelfOutOffsetArray = OffsetArray<PartnerSelfOut>

inline fun PartnerSelfOutOffsetArray(size: Int, crossinline call: (Int) -> Offset<PartnerSelfOut>): PartnerSelfOutOffsetArray =
    PartnerSelfOutOffsetArray(IntArray(size) { call(it).value })
