// automatically generated by the FlatBuffers compiler, do not modify

package ffiData

import com.google.flatbuffers.kotlin.*
import kotlin.jvm.JvmInline
@Suppress("unused")
class PartnerSelfIn : Table() {

    fun init(i: Int, buffer: ReadWriteBuffer) : PartnerSelfIn = reset(i, buffer)

    val id : base.UlidBytes? get() = id(base.UlidBytes())
    fun id(obj: base.UlidBytes) : base.UlidBytes? = lookupField(4, null ) { obj.init(it + bufferPos, bb) }

    companion object {
        @JvmStatic
        fun validateVersion() = VERSION_2_0_8

        @JvmStatic
        fun asRoot(buffer: ReadWriteBuffer) : PartnerSelfIn = asRoot(buffer, PartnerSelfIn())
        @JvmStatic
        fun asRoot(buffer: ReadWriteBuffer, obj: PartnerSelfIn) : PartnerSelfIn = obj.init(buffer.getInt(buffer.limit) + buffer.limit, buffer)


        @JvmStatic
        fun startPartnerSelfIn(builder: FlatBufferBuilder) = builder.startTable(1)

        @JvmStatic
        fun addId(builder: FlatBufferBuilder, id: Offset<base.UlidBytes>) = builder.addStruct(0, id.value, 0)

        @JvmStatic
        fun endPartnerSelfIn(builder: FlatBufferBuilder) : Offset<PartnerSelfIn> {
            val o: Offset<PartnerSelfIn> = builder.endTable()
            return o
        }
    }
}

typealias PartnerSelfInOffsetArray = OffsetArray<PartnerSelfIn>

inline fun PartnerSelfInOffsetArray(size: Int, crossinline call: (Int) -> Offset<PartnerSelfIn>): PartnerSelfInOffsetArray =
    PartnerSelfInOffsetArray(IntArray(size) { call(it).value })
