// automatically generated by the FlatBuffers compiler, do not modify

package partner

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class OnLine : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : OnLine {
        __init(_i, _bb)
        return this
    }
    val header : base.Header? get() = header(base.Header())
    fun header(obj: base.Header) : base.Header? {
        val o = __offset(4)
        return if (o != 0) {
            obj.__assign(o + bb_pos, bb)
        } else {
            null
        }
    }
    val partner : partner.Partner? get() = partner(partner.Partner())
    fun partner(obj: partner.Partner) : partner.Partner? {
        val o = __offset(6)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    val ts : base.Timestamp? get() = ts(base.Timestamp())
    fun ts(obj: base.Timestamp) : base.Timestamp? {
        val o = __offset(8)
        return if (o != 0) {
            obj.__assign(o + bb_pos, bb)
        } else {
            null
        }
    }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsOnLine(_bb: ByteBuffer): OnLine = getRootAsOnLine(_bb, OnLine())
        fun getRootAsOnLine(_bb: ByteBuffer, obj: OnLine): OnLine {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun startOnLine(builder: FlatBufferBuilder) = builder.startTable(3)
        fun addHeader(builder: FlatBufferBuilder, header: Int) = builder.addStruct(0, header, 0)
        fun addPartner(builder: FlatBufferBuilder, partner: Int) = builder.addOffset(1, partner, 0)
        fun addTs(builder: FlatBufferBuilder, ts: Int) = builder.addStruct(2, ts, 0)
        fun endOnLine(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
