// automatically generated by the FlatBuffers compiler, do not modify

package partner

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class Partner : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : Partner {
        __init(_i, _bb)
        return this
    }
    val id : base.UlidBytes? get() = id(base.UlidBytes())
    fun id(obj: base.UlidBytes) : base.UlidBytes? {
        val o = __offset(4)
        return if (o != 0) {
            obj.__assign(o + bb_pos, bb)
        } else {
            null
        }
    }
    fun terminalIds(j: Int) : base.TerminalId? = terminalIds(base.TerminalId(), j)
    fun terminalIds(obj: base.TerminalId, j: Int) : base.TerminalId? {
        val o = __offset(6)
        return if (o != 0) {
            obj.__assign(__vector(o) + j * 16, bb)
        } else {
            null
        }
    }
    val terminalIdsLength : Int
        get() {
            val o = __offset(6); return if (o != 0) __vector_len(o) else 0
        }
    val partnerId : base.UByte16? get() = partnerId(base.UByte16())
    fun partnerId(obj: base.UByte16) : base.UByte16? {
        val o = __offset(8)
        return if (o != 0) {
            obj.__assign(o + bb_pos, bb)
        } else {
            null
        }
    }
    val name : String?
        get() {
            val o = __offset(10)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val nameAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(10, 1)
    fun nameInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 10, 1)
    val showName : String?
        get() {
            val o = __offset(12)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val showNameAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(12, 1)
    fun showNameInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 12, 1)
    val ip : String?
        get() {
            val o = __offset(14)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val ipAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(14, 1)
    fun ipInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 14, 1)
    val port : Short
        get() {
            val o = __offset(16)
            return if(o != 0) bb.getShort(o + bb_pos) else 0
        }
    val createTs : base.Timestamp? get() = createTs(base.Timestamp())
    fun createTs(obj: base.Timestamp) : base.Timestamp? {
        val o = __offset(18)
        return if (o != 0) {
            obj.__assign(o + bb_pos, bb)
        } else {
            null
        }
    }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsPartner(_bb: ByteBuffer): Partner = getRootAsPartner(_bb, Partner())
        fun getRootAsPartner(_bb: ByteBuffer, obj: Partner): Partner {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun startPartner(builder: FlatBufferBuilder) = builder.startTable(8)
        fun addId(builder: FlatBufferBuilder, id: Int) = builder.addStruct(0, id, 0)
        fun addTerminalIds(builder: FlatBufferBuilder, terminalIds: Int) = builder.addOffset(1, terminalIds, 0)
        fun startTerminalIdsVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(16, numElems, 8)
        fun addPartnerId(builder: FlatBufferBuilder, partnerId: Int) = builder.addStruct(2, partnerId, 0)
        fun addName(builder: FlatBufferBuilder, name: Int) = builder.addOffset(3, name, 0)
        fun addShowName(builder: FlatBufferBuilder, showName: Int) = builder.addOffset(4, showName, 0)
        fun addIp(builder: FlatBufferBuilder, ip: Int) = builder.addOffset(5, ip, 0)
        fun addPort(builder: FlatBufferBuilder, port: Short) = builder.addShort(6, port, 0)
        fun addCreateTs(builder: FlatBufferBuilder, createTs: Int) = builder.addStruct(7, createTs, 0)
        fun endPartner(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
        fun finishPartnerBuffer(builder: FlatBufferBuilder, offset: Int) = builder.finish(offset)
        fun finishSizePrefixedPartnerBuffer(builder: FlatBufferBuilder, offset: Int) = builder.finishSizePrefixed(offset)
    }
}
